  name: ETablePerms
  author: skyss0fly
  api: 5.0.0
  version: 1.0
  description: "simple enchanting table permissions plugin"
  main: skyss0fly\ETablePerms\Main
  permissions:
   EtablePerms.Use:
   default: false
   description: "allows usage of enchanting tables"
